# Generated by Django 5.1.1 on 2024-09-20 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumApp', '0003_urls_alter_post_author_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
