# Generated by Django 5.1.1 on 2024-09-21 19:34

import Petstagram.photos.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[Petstagram.photos.validators.ValidateImageSize()])),
                ('description', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)])),
                ('location', models.TextField(max_length=30)),
                ('date_of_publication', models.DateTimeField(auto_now=True)),
                ('tagged_pets', models.ManyToManyField(to='pets.pet')),
            ],
        ),
    ]
