# Generated by Django 5.1.2 on 2024-10-23 18:31

import MyPlant.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', MyPlant.accounts.models.NameField()),
                ('last_name', MyPlant.accounts.models.NameField()),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
