# Generated by Django 5.0.4 on 2024-07-29 12:25

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objcets', django.db.models.manager.Manager()),
            ],
        ),
    ]
