# Generated by Django 5.1.2 on 2024-10-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('1', 'Indoor Plants'), ('2', 'Outdoor Plants')], max_length=14),
        ),
    ]
