# Generated by Django 5.0.4 on 2024-07-22 19:44

import django.core.validators
import django.db.models.deletion
import main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TennisPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, validators=[main_app.validators.RangeLengthValidator(5, 120)])),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=100, validators=[main_app.validators.RangeLengthValidator(2, 100)])),
                ('ranking', models.PositiveIntegerField(validators=[main_app.validators.RangeValueValidator(1, 300)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, validators=[main_app.validators.RangeLengthValidator(2, 150)])),
                ('location', models.CharField(max_length=100, validators=[main_app.validators.RangeLengthValidator(2, 100)])),
                ('prize_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('surface_type', models.CharField(choices=[('Not Selected', 'Not Selected'), ('Clay', 'Clay'), ('Grass', 'Grass'), ('Hard Court', 'Hard Court')], default='Not Selected', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=100)),
                ('summary', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('date_played', models.DateTimeField()),
                ('players', models.ManyToManyField(related_name='matches', to='main_app.tennisplayer')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.tennisplayer')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tournament')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
