# Generated by Django 5.1.2 on 2024-10-27 07:43

import django.core.validators
import regular_exam_project_27102024.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), regular_exam_project_27102024.common.validators.IsAlphaValidator(message='Your name must contain letters only!')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), regular_exam_project_27102024.common.validators.IsAlphaValidator(message='Your name must contain letters only!')])),
                ('passcode', models.CharField(help_text='Your passcode must be a combination of 6 digits', validators=[regular_exam_project_27102024.common.validators.ExactLengthValidator(6, 'Your passcode must be exactly 6 digits!')])),
                ('pets_number', models.PositiveSmallIntegerField()),
                ('info', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
