# Generated by Django 5.1.1 on 2024-10-06 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
