# Generated by Django 5.0.4 on 2024-06-22 18:32

from django.db import migrations

def add_item_data(apps, schema_editor):
    Item = apps.get_model("main_app","Item")
    for item in Item.objects.all():
        if item.price <= 10:
            item.rarity = "Rare"
        elif item.price <= 20:
            item.rarity = "Very Rare"
        elif item.price <= 30:
            item.rarity = "Extremely Rare"
        else:
            item.rarity = "Mega Rare"
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_item'),
    ]

    operations = [
        migrations.RunPython(add_item_data)
    ]
